databases:
  - name: temporal-db
    databaseName: temporal
    user: temporal
    plan: Starter
    region: frankfurt

services:
  - type: pserv
    name: temporal
    autoDeploy: false
    plan: Starter
    region: frankfurt
    env: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: SERVICES
        value: frontend,matching,history,worker
      - key: DYNAMIC_CONFIG_FILE_PATH
        value: /etc/temporal/dynamicconfig.yaml
      - key: BIND_ON_IP
        value: 0.0.0.0
      - key: TEMPORAL_BROADCAST_ADDRESS
        value: 0.0.0.0
      - key: TEMPORAL_CLI_ADDRESS
        value: localhost:7233
      - key: SKIP_POSTGRES_DB_CREATION
        value: true
      - key: DB
        value: postgresql
      - key: DBNAME
        fromDatabase:
          name: temporal-db
          property: database
      - key: DB_PORT
        fromDatabase:
          name: temporal-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: temporal-db
          property: user
      - key: POSTGRES_PWD
        fromDatabase:
          name: temporal-db
          property: password
      - key: POSTGRES_SEEDS
        fromDatabase:
          name: temporal-db
          property: host
